config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  # match ':controller(/:action(/:id))(.:format)'
  resources :franchisers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/franchiser.rb
class Franchiser < ApplicationRecord


  validates_format_of :contact_name, :with => /[^u4E00-u9FA5]/, :message => "只能输入中文"
  CONTACTTYPE = {'0' => '销售', '1' => '技术支持', '2' => '维修'}
  ISLEAVED = {0 => '否', 1 => '是'}
  ROLE = {0 => '系统管理员', 1 => '经销商管理员', 2 => '普通经销商用户'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
end

app/controllers/franchisers_controller.rb
class FranchisersController < ApplicationController
  layout 'admin'
  def index
    list
    render('list')
  end

  def list
    @franchisers = Franchiser.order('contact_name ASC')
  end

  def new
    @franchiser = Franchiser.new()
  end

  def create
    @franchiser = Franchiser.new()
    if @franchiser.save
      flash[:notice] = 'franchiser Created'
      redirect_to(:action => 'list')
    else
      render('new')
    end

  end

  def show

  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
end

app/controllers/product_type_controller.rb
class ProductTypeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/franchisers_helper.rb
module FranchisersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/product_type_helper.rb
module ProductTypeHelper
end

app/views/franchisers/_form.html.erb
<table width="100%" class="table">
  <tbody>
      <tr>
        <td width="8%">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>
        <td><%=  f.text_field :contact_name %></td>
      </tr>
      <td>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>
        <td><%=  f.text_field :email %></td>
      </tr>
      <tr>
        <td>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;务:</td>
        <td><%=  f.text_field :headship %></td>
      </tr>
      <%# if @franchiser.new_record? %>
      <tr>
        <td>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;能:</td>
        <td>
          <select>
            <option>销售</option>
            <option>技术支持</option>
            <option>维修</option>
          </select>
        </td>
      </tr>
      <%# end %>
      <tr>
        <td>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话:</td>
        <td><%=  f.text_field :phone %></td>
      </tr>
      <%# if  @franchiser.new_record? || (current_franchiser.role != 2 && !@franchiser.new_record? ) %>
      <tr>
        <td>是否离职:</td>
        <td>
          <%=  f.check_box :is_leaved %>
        </td>
      </tr>
      <%# end %>
      <tr>
        <td>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;编:</td>
        <td><%=  f.text_field :zip %></td>
      </tr>
      <tr>
        <td>传&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;真:</td>
        <td><%=  f.text_field :fax %></td>

      </tr>
      <tr>
        <td>通讯地址:</td>
        <td><%= f.text_field :address %></td>
      </tr>
     </tbody>
</table>
<div class="control-group">
  <div class="controls">
    <button type="submit" class="btn btn-primary">保存</button>
  </div>
</div>

app/views/franchisers/index.html.erb
测试数据

app/views/franchisers/list.html.erb
<div class="row">
  <div class="span4 span_margin"><h4>用户列表</h4></div>
  <div class="span6">
    <% if (true) %>
        <span class="navbar-text pull-right span_margin"><%#=  link_to "新增用户", new_franchiser_path, :class => "btn" %></span>
    <% end %>
  </div>
</div>
<table class="table table-striped">
    <tr>
      <td>姓名</td>
      <td>登录名</td>
      <td>邮箱</td>
      <td>角色</td>
      <td>是否离职</td>
      <td>公司</td>
      <td width="15%">操作</td>
    </tr>
  <% if @franchisers.blank? %>
  <tr><td colspan="7" style="text-align: center">没有数据</td></tr>
      <% end %>
  <% @franchisers.each do |franchiser| %>
    <tr>
      <td><%= franchiser.contact_name %></td>
      <td><%= franchiser.phone %></td>
      <td><%= franchiser.email %></td>
      <td><%=  franchiser.address %></td>
        <td><%= franchiser.is_leaved %></td>
      <td><%=  franchiser.company_id %></td>
      <td>

      </td>
    </tr>
  <% end %>
</table>
<div class="control-group">
  <div class="controls">

  </div>
</div>

app/views/franchisers/new.html.erb
<h1>新增用户</h1>

<div class="franchiser new">
  <h2>Create Franchiser</h2>
  <%= form_for(:franchiser, :url => {:action => 'create'}) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f})%>
  <% end%>
</div>

app/views/franchisers/show.html.erb
<table width='100%' class="table">
  <thead>
  <tr><td colspan="2"><h4>用户详细</h4></td></tr>
  </thead>
  <tbody>
    <tr>
      <td width="8%">姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名:</td>
      <td>测试数据</td>
    </tr>
    <tr>
      <td width="8%">登&nbsp;&nbsp;&nbsp;录名:</td>
      <td>用户名</td?
    </tr>
    <tr>
      <td>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱:</td>
      <td><%= @franchiser.email %></td>
    </tr>
    <tr>
      <td>角&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;色:</td>
      <td><%= Franchiser::ROLE[@franchiser.role] %></td>
    </tr>
    <tr>
      <td>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;务:</td>
      <td>
             <%= @franchiser.headship %>
      </td>
    </tr>
    <tr>
      <td>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;能:</td>
      <td><%=  Franchiser::CONTACTTYPE[@franchiser.contact_type]  %></td>
    </tr>
    <tr>
      <td>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话:</td>
      <td><%= @franchiser.phone %></td>
    </tr>
    <tr>
          <td>是否离职:</td>
          <td><%= Franchiser::ISLEAVED[@franchiser.is_leaved] %></td>
        </tr>
        <tr>
          <td>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;编:</td>
          <td><%= @franchiser.zip %></td>
        </tr>
        <tr>
          <td>传&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;真:</td>
          <td><%= @franchiser.fax %></td>
        </tr>
        <tr>
          <td>通讯地址:</td>
          <td><%= @franchiser.address %></td>
        </tr>
        <tr>
          <td>公&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;司:</td>
          <td><%= @franchiser.address %></td>
        </tr>

  </tbody>
</table>
<div class="control-group">
  <div class="controls">
   <%=  link_to "返回", franchisers_path, :class => "btn" %>
  </div>
</div>

<% content_for :navigation do %>
    <% if current_franchiser.is_super_admin? %>
        <%= render :partial => "layouts/include/sys_set_left_navi/system_setting_left_navigation_#{get_title[1]}" %>

        <% else %>
        <%= render :partial => "layouts/include/p_type_left_navi/product_type_left_navigation_#{get_title[1]}" %>
        <% end %>

<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Product</title>
		<%= stylesheet_link_tag('public', 'admin', :media => 'all') %>
		<%= javascript_include_tag('application') %>
  </head>
  <body>
    <div id="header">
      <h1>Simple CMS Admin</h1>
    </div>
    <div id="main">
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <p id="copyright">&copy; hychou.net </p>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FactoryCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>